# Generated by Django 4.1.4 on 2023-03-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0003_alter_cust_cheque_book_alter_cust_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust',
            name='Account_type',
            field=models.CharField(max_length=20),
        ),
    ]
